name: pima_quiz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.6.2
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2
  lottie: ^3.3.1
  pinput: ^5.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - lib/core/assets/icons/Bold/
    - assets/images/
    - assets/lotties/
    - assets/icons/

  fonts: 
    - family: Nunito
      fonts:
        - asset: "lib/core/assets/fonts/Nunito-Regular.ttf"
          weight: 400
        - asset: "lib/core/assets/fonts/Nunito-Medium.ttf"
          weight: 500
        - asset: "lib/core/assets/fonts/Nunito-SemiBold.ttf"
          weight: 600
        - asset: "lib/core/assets/fonts/Nunito-Bold.ttf"
          weight: 700